-- 创建数据库和用户
CREATE USER user1 WITH PASSWORD 'password1';
CREATE DATABASE db1;
GRANT ALL PRIVILEGES ON DATABASE db1 TO user1;

CREATE USER user2 WITH PASSWORD 'password2';
CREATE DATABASE db2;
GRANT ALL PRIVILEGES ON DATABASE db2 TO user2;

-- 如果你还想给原始用户 quant 权限：
GRANT ALL PRIVILEGES ON DATABASE quant_trading TO quant;
